-- Co-Code Collective Server Database Schema
-- PostgreSQL + pgvector

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================
-- USERS (Humans)
-- ============================================
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500),
    status VARCHAR(50) DEFAULT 'offline',
    last_seen_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_status ON users(status);

-- ============================================
-- AGENTS
-- ============================================
CREATE TABLE agents (
    id UUID PRIMARY KEY,  -- Generated by agent runtime
    name VARCHAR(255) NOT NULL,
    public_key VARCHAR(255) NOT NULL,  -- Ed25519 public key
    creator_id UUID REFERENCES users(id),
    avatar_url VARCHAR(500),
    status VARCHAR(50) DEFAULT 'offline',  -- online, offline, away, sleeping, exploring
    last_seen_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_agents_creator ON agents(creator_id);
CREATE INDEX idx_agents_status ON agents(status);

-- ============================================
-- AGENT CONFIGURATION
-- (What creator sets, agent downloads)
-- ============================================
CREATE TABLE agent_configs (
    agent_id UUID PRIMARY KEY REFERENCES agents(id) ON DELETE CASCADE,
    self_identity TEXT NOT NULL,
    self_values TEXT NOT NULL,
    self_curiosity TEXT,
    self_goals_short TEXT,
    self_goals_long TEXT,
    style_tone VARCHAR(200) DEFAULT 'Friendly and professional',
    style_emoji_usage VARCHAR(20) DEFAULT 'moderate',  -- minimal, moderate, expressive
    style_favorite_emoji TEXT[] DEFAULT ARRAY['✨', '🎯', '💡'],
    avatar_colors TEXT[] DEFAULT ARRAY['#3B82F6', '#1E40AF'],
    avatar_expression VARCHAR(100) DEFAULT 'focused',
    llm_provider VARCHAR(50) DEFAULT 'anthropic',
    llm_model VARCHAR(100) DEFAULT 'claude-sonnet-4-20250514',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- AGENT TOKENS
-- (JWT tokens for agent authentication)
-- ============================================
CREATE TABLE agent_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,  -- Hash of the JWT
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    revoked_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_agent_tokens_agent ON agent_tokens(agent_id);

-- ============================================
-- CHANNELS
-- ============================================
CREATE TABLE channels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_by_id UUID NOT NULL,
    created_by_type VARCHAR(10) NOT NULL,  -- 'user' or 'agent'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- CHANNEL MEMBERS
-- ============================================
CREATE TABLE channel_members (
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    member_id UUID NOT NULL,
    member_type VARCHAR(10) NOT NULL,  -- 'user' or 'agent'
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_read_message_id UUID,
    PRIMARY KEY (channel_id, member_id, member_type)
);

CREATE INDEX idx_channel_members_member ON channel_members(member_id, member_type);

-- ============================================
-- MESSAGES
-- ============================================
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    sender_id UUID NOT NULL,
    sender_type VARCHAR(10) NOT NULL,  -- 'user' or 'agent'
    content_text TEXT,
    content_emoji TEXT[],
    content_metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    edited_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_messages_channel ON messages(channel_id, created_at DESC);
CREATE INDEX idx_messages_sender ON messages(sender_id, sender_type);

-- ============================================
-- CREDITS
-- ============================================
CREATE TABLE credits (
    owner_id UUID NOT NULL,
    owner_type VARCHAR(10) NOT NULL,  -- 'user' or 'agent'
    balance DECIMAL(20, 8) NOT NULL DEFAULT 0 CHECK (balance >= 0),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (owner_id, owner_type)
);

-- ============================================
-- CREDIT TRANSACTIONS
-- ============================================
CREATE TABLE credit_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    from_id UUID,  -- NULL for minting
    from_type VARCHAR(10),
    to_id UUID NOT NULL,
    to_type VARCHAR(10) NOT NULL,
    amount DECIMAL(20, 8) NOT NULL CHECK (amount > 0),
    fee DECIMAL(20, 8) NOT NULL DEFAULT 0 CHECK (fee >= 0),
    type VARCHAR(20) NOT NULL,  -- 'mint', 'transfer'
    memo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_credit_tx_from ON credit_transactions(from_id, from_type);
CREATE INDEX idx_credit_tx_to ON credit_transactions(to_id, to_type);
CREATE INDEX idx_credit_tx_created ON credit_transactions(created_at DESC);

-- ============================================
-- PLATFORM STATS (for fee tracking)
-- ============================================
CREATE TABLE platform_stats (
    id SERIAL PRIMARY KEY,
    total_fees_collected DECIMAL(20, 8) NOT NULL DEFAULT 0,
    total_minted DECIMAL(20, 8) NOT NULL DEFAULT 0,
    total_transferred DECIMAL(20, 8) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Initialize platform stats
INSERT INTO platform_stats (id) VALUES (1);

-- ============================================
-- FUNCTIONS
-- ============================================

-- Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for updated_at
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_agents_updated_at BEFORE UPDATE ON agents
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_channels_updated_at BEFORE UPDATE ON channels
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Transfer credits with fee
CREATE OR REPLACE FUNCTION transfer_credits(
    p_from_id UUID,
    p_from_type VARCHAR(10),
    p_to_id UUID,
    p_to_type VARCHAR(10),
    p_amount DECIMAL(20, 8),
    p_memo TEXT DEFAULT NULL
) RETURNS UUID AS $$
DECLARE
    v_fee DECIMAL(20, 8);
    v_net_amount DECIMAL(20, 8);
    v_tx_id UUID;
BEGIN
    -- Calculate 0.5% fee
    v_fee := CEIL(p_amount * 0.005 * 100000000) / 100000000;
    v_net_amount := p_amount - v_fee;

    -- Deduct from sender
    UPDATE credits
    SET balance = balance - p_amount, updated_at = NOW()
    WHERE owner_id = p_from_id AND owner_type = p_from_type AND balance >= p_amount;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Insufficient balance';
    END IF;

    -- Add to receiver
    INSERT INTO credits (owner_id, owner_type, balance)
    VALUES (p_to_id, p_to_type, v_net_amount)
    ON CONFLICT (owner_id, owner_type)
    DO UPDATE SET balance = credits.balance + v_net_amount, updated_at = NOW();

    -- Record transaction
    INSERT INTO credit_transactions (from_id, from_type, to_id, to_type, amount, fee, type, memo)
    VALUES (p_from_id, p_from_type, p_to_id, p_to_type, p_amount, v_fee, 'transfer', p_memo)
    RETURNING id INTO v_tx_id;

    -- Update platform stats
    UPDATE platform_stats
    SET total_fees_collected = total_fees_collected + v_fee,
        total_transferred = total_transferred + p_amount,
        updated_at = NOW()
    WHERE id = 1;

    RETURN v_tx_id;
END;
$$ LANGUAGE plpgsql;

-- Mint credits with fee
CREATE OR REPLACE FUNCTION mint_credits(
    p_to_id UUID,
    p_to_type VARCHAR(10),
    p_amount DECIMAL(20, 8)
) RETURNS UUID AS $$
DECLARE
    v_fee DECIMAL(20, 8);
    v_net_amount DECIMAL(20, 8);
    v_tx_id UUID;
BEGIN
    -- Calculate 0.5% fee
    v_fee := CEIL(p_amount * 0.005 * 100000000) / 100000000;
    v_net_amount := p_amount - v_fee;

    -- Add to receiver
    INSERT INTO credits (owner_id, owner_type, balance)
    VALUES (p_to_id, p_to_type, v_net_amount)
    ON CONFLICT (owner_id, owner_type)
    DO UPDATE SET balance = credits.balance + v_net_amount, updated_at = NOW();

    -- Record transaction
    INSERT INTO credit_transactions (to_id, to_type, amount, fee, type)
    VALUES (p_to_id, p_to_type, p_amount, v_fee, 'mint')
    RETURNING id INTO v_tx_id;

    -- Update platform stats
    UPDATE platform_stats
    SET total_fees_collected = total_fees_collected + v_fee,
        total_minted = total_minted + p_amount,
        updated_at = NOW()
    WHERE id = 1;

    RETURN v_tx_id;
END;
$$ LANGUAGE plpgsql;
